const TASKS = [
  { id: 'coffee', label: 'coffee run', icon: '☕' },
  { id: 'grocery', label: 'grocery run', icon: '🛒' },
  { id: 'dog', label: 'dog walk', icon: '🐕' },
  { id: 'run', label: 'run', icon: '🏃' },
  { id: 'picnic', label: 'picnic', icon: '🧺' },
  { id: 'photo', label: 'photography', icon: '📷' },
  { id: 'windows', label: 'open windows', icon: '🪟' },
];

const state = { taskId: 'coffee', location: null, weather: null, air: null, places: [], forecastHours: [], city: '', coords: null };
const $ = (id) => document.getElementById(id);
const els = { locationLine: $('locationLine'), recommendation: $('recommendation'), summary: $('summary'), chips: $('chips'), statsGrid: $('statsGrid'), windowsList: $('windowsList'), placesList: $('placesList'), offlineLine: $('offlineLine'), cityInput: $('cityInput'), searchBtn: $('searchBtn'), refreshBtn: $('refreshBtn'), installBtn: $('installBtn') };

function fmtTemp(v){ return `${Math.round(v)}°`; }
function fmtTime(ts){ return new Intl.DateTimeFormat([], { hour: 'numeric' }).format(new Date(ts)); }
function pct(v){ return `${Math.round(v)}%`; }
function clamp(v,min,max){ return Math.max(min, Math.min(max, v)); }
function scoreHour(h, task){ const temp = h.temperature_2m; const wind = h.wind_speed_10m ?? 0; const rain = h.precipitation ?? 0; const cloud = h.cloud_cover ?? 0; const uv = h.uv_index ?? 0; const aqi = state.air?.hourly?.us_aqi?.[h.index] ?? state.air?.hourly?.pm2_5?.[h.index] ?? 0; let s = 50; if(task==='run'){ s += clamp((18-Math.abs(temp-14))*3, -20, 18) + clamp((12-wind)*2, -20, 20) - rain*10 - aqi/4; }
  else if(task==='picnic'){ s += clamp((24-Math.abs(temp-20))*2.5,-15,12) - rain*11 - wind*2 - cloud*.2; }
  else if(task==='windows'){ s += clamp((16-Math.abs(temp-18))*3,-10,15) - rain*12 + clamp((14-wind)*1.4,-12,8); }
  else if(task==='photo'){ s += clamp((18-Math.abs(temp-16))*1.5,-8,10) + (cloud>35&&cloud<80?10:0) - rain*8 - wind*1.5; }
  else if(task==='dog'){ s += clamp((20-Math.abs(temp-15))*2.2,-12,12) - rain*10 - wind; }
  else { s += clamp((22-Math.abs(temp-18))*1.2,-8,10) - rain*9 - wind*1.2; }
  return s; }
function recommendationFromScore(s){ if(s>=72) return ['go','Go now']; if(s>=52) return ['wait','Wait']; return ['skip','Skip today']; }
function saveCache(){ localStorage.setItem('gosignal:last', JSON.stringify({ ...state, savedAt: Date.now() })); }
function loadCache(){ try { return JSON.parse(localStorage.getItem('gosignal:last')||'null'); } catch { return null; } }
function renderChips(){ els.chips.innerHTML=''; TASKS.forEach(t=>{ const b=document.importNode($('chipTpl').content,true).querySelector('button'); b.textContent=`${t.icon} ${t.label}`; b.classList.toggle('active', t.id===state.taskId); b.onclick=()=>{ state.taskId=t.id; renderAll(); }; els.chips.appendChild(b); }); }
function renderAll(){ renderChips(); if(!state.weather){ return; } const task = TASKS.find(t=>t.id===state.taskId).label; const hours = state.forecastHours.slice(0,12); const scored = hours.map((h,i)=>({ ...h, index:i, score: scoreHour(h, state.taskId) })).sort((a,b)=>b.score-a.score); const best = scored[0]; const [kind,label] = recommendationFromScore(best.score); els.recommendation.className = `recommendation ${kind}`; els.recommendation.textContent = label; els.summary.textContent = `${task} looks best around ${fmtTime(best.time)} with ${fmtTemp(best.temperature_2m)} and ${Math.round(best.score)} / 100 conditions.`; els.locationLine.textContent = `${state.location?.name || 'Current location'} · ${state.location?.admin1 || state.location?.country || ''}`.replace(/ · $/,'');
  const st = [ ['Temp', fmtTemp(state.weather.current.temperature_2m)], ['Feels like', fmtTemp(state.weather.current.apparent_temperature)], ['Wind', `${Math.round(state.weather.current.wind_speed_10m)} km/h`], ['Rain', `${state.weather.current.precipitation} mm`], ['Clouds', pct(state.weather.current.cloud_cover)], ['AQI', state.air?.current?.us_aqi ?? 'n/a'], ['Humidity', pct(state.weather.current.relative_humidity_2m)], ['UV', state.weather.current.uv_index ?? 'n/a'] ]; els.statsGrid.innerHTML=''; st.forEach(([l,v])=>{ const n=document.importNode($('statTpl').content,true).firstElementChild; n.querySelector('.label').textContent=l; n.querySelector('.value').textContent=v; els.statsGrid.appendChild(n); }); els.windowsList.innerHTML=''; scored.slice(0,5).forEach(h=>{ const n=document.importNode($('windowTpl').content,true).firstElementChild; n.querySelector('.window-time').textContent=`${fmtTime(h.time)} · ${Math.round(h.score)} / 100`; n.querySelector('.window-meta').textContent=`${fmtTemp(h.temperature_2m)}, wind ${Math.round(h.wind_speed_10m)} km/h, rain ${h.precipitation} mm`; els.windowsList.appendChild(n); }); els.placesList.innerHTML=''; if(state.places.length){ state.places.slice(0,6).forEach(p=>{ const n=document.importNode($('placeTpl').content,true).firstElementChild; n.querySelector('.place-name').textContent=p.name; n.querySelector('.place-kind').textContent=p.kind; n.querySelector('.place-meta').textContent=`${p.distance} m away`; els.placesList.appendChild(n); }); } else { els.placesList.innerHTML = '<div class="muted">No nearby places loaded yet.</div>'; } els.offlineLine.textContent = `Cached ${new Date(loadCache()?.savedAt || Date.now()).toLocaleString()}.`; saveCache(); }
async function fetchJson(url){ const r = await fetch(url,{headers:{'Accept':'application/json'}}); if(!r.ok) throw new Error(`${r.status} ${r.statusText}`); return r.json(); }
async function lookupCity(q){ const data = await fetchJson(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(q)}&count=1&language=en&format=json`); return data.results?.[0] || null; }
async function getForecast(lat,lon){ const url = new URL('https://api.open-meteo.com/v1/forecast'); url.search = new URLSearchParams({ latitude:lat, longitude:lon, current:['temperature_2m','apparent_temperature','relative_humidity_2m','precipitation','cloud_cover','wind_speed_10m','uv_index'].join(','), hourly:['temperature_2m','precipitation','cloud_cover','wind_speed_10m','uv_index'].join(','), forecast_days:'1', timezone:'auto' }).toString(); return fetchJson(url); }
async function getAir(lat,lon){ const url = new URL('https://air-quality-api.open-meteo.com/v1/air-quality'); url.search = new URLSearchParams({ latitude:lat, longitude:lon, current:'us_aqi,pm2_5,pm10', hourly:'us_aqi,pm2_5,pm10', timezone:'auto' }).toString(); return fetchJson(url); }
async function getPlaces(lat,lon,taskId){ const tags = { coffee:'cafe', grocery:'supermarket', dog:'dog_park', run:'park', picnic:'park', photo:'viewpoint', windows:'park' }[taskId] || 'park'; const q = `[out:json][timeout:20];(node["amenity"="${tags}"](around:2500,${lat},${lon});way["amenity"="${tags}"](around:2500,${lat},${lon});relation["amenity"="${tags}"](around:2500,${lat},${lon});node["leisure"="${tags}"](around:2500,${lat},${lon});way["leisure"="${tags}"](around:2500,${lat},${lon}););out center 20;`; const r = await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:`data=${encodeURIComponent(q)}`}); const data = await r.json(); return (data.elements||[]).map(el=>{ const lat2 = el.lat ?? el.center?.lat; const lon2 = el.lon ?? el.center?.lon; return { name: el.tags?.name || tags, kind: el.tags?.amenity || el.tags?.leisure || 'place', distance: Math.round(distance(lat,lon,lat2,lon2)) }; }).sort((a,b)=>a.distance-b.distance); }
function distance(lat1,lon1,lat2,lon2){ const R=6371e3, p=Math.PI/180; const a=.5-.5*Math.cos((lat2-lat1)*p)+Math.cos(lat1*p)*Math.cos(lat2*p)*(.5-.5*Math.cos((lon2-lon1)*p)); return 2*R*Math.asin(Math.sqrt(a)); }
async function loadLocation(lat,lon,city=''){ state.coords={lat,lon}; state.city=city; const geo = city || `${lat.toFixed(2)}, ${lon.toFixed(2)}`; els.locationLine.textContent = `Loading ${geo}…`; const [weather, air, places] = await Promise.all([getForecast(lat,lon), getAir(lat,lon), getPlaces(lat,lon,state.taskId).catch(()=>[])]); state.weather=weather; state.air=air; state.forecastHours = weather.hourly.time.map((time,i)=>({ time, temperature_2m: weather.hourly.temperature_2m[i], precipitation: weather.hourly.precipitation[i], cloud_cover: weather.hourly.cloud_cover[i], wind_speed_10m: weather.hourly.wind_speed_10m[i], uv_index: weather.hourly.uv_index[i] })); state.places=places; state.location = { name: city || weather.timezone, admin1:'', country:'' }; renderAll(); }
async function locate(){ try { const pos = await new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,{enableHighAccuracy:true,timeout:10000})); await loadLocation(pos.coords.latitude,pos.coords.longitude,'Current location'); } catch { const cache = loadCache(); if(cache?.weather){ Object.assign(state, cache); renderAll(); } els.locationLine.textContent = 'Location blocked, search a city instead.'; } }
async function doSearch(){ const q = els.cityInput.value.trim(); if(!q) return; els.summary.textContent='Searching…'; const hit = await lookupCity(q); if(!hit){ els.summary.textContent='No city found. Try a larger nearby place.'; return; } await loadLocation(hit.latitude, hit.longitude, hit.name); }
function setupInstall(){ let deferred; window.addEventListener('beforeinstallprompt', e=>{ e.preventDefault(); deferred=e; els.installBtn.classList.remove('hidden'); }); els.installBtn.onclick=async()=>{ if(!deferred) return; deferred.prompt(); await deferred.userChoice; deferred=null; els.installBtn.classList.add('hidden'); }; }
async function init(){ renderChips(); const cache = loadCache(); if(cache?.weather){ Object.assign(state, cache); renderAll(); } setupInstall(); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{}); els.searchBtn.onclick = doSearch; els.refreshBtn.onclick = ()=> state.coords ? loadLocation(state.coords.lat,state.coords.lon,state.city) : locate(); els.cityInput.addEventListener('keydown', e=>{ if(e.key==='Enter') doSearch(); }); await locate(); }
init().catch(err=>{ els.summary.textContent = `Unable to load data: ${err.message}`; });
